# Generated by Django 4.2.6 on 2023-11-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Имя',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Фамилия',
        ),
    ]
